directories:
  output: dist-electron
  buildResources: build
appId: com.github.yarik-osg.dmarket-bot
productName: DMarket Bot
files:
  - filter:
      - main/**/*
      - renderer/dist/**/*
      - package.json
publish:
  - provider: github
    owner: Yarik-osg
    repo: Dmarket_js_bot
win:
  target:
    - nsis
  verifyUpdateCodeSignature: false
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  differentialPackage: true
mac:
  target:
    - zip
    - dmg
  category: public.app-category.finance
electronVersion: 33.4.11
